#ifndef _SEP2P_ERROR___INC_H_
#define _SEP2P_ERROR___INC_H_

#define ERROR_SEP2P_SUCCESSFUL						0
#define ERROR_SEP2P_NOT_INITIALIZED					-1
#define ERROR_SEP2P_ALREADY_INITIALIZED				-2
#define ERROR_SEP2P_TIME_OUT							-3
#define ERROR_SEP2P_INVALID_ID						-4
#define ERROR_SEP2P_INVALID_PARAMETER				-5
#define ERROR_SEP2P_DEVICE_NOT_ONLINE				-6
#define ERROR_SEP2P_FAIL_TO_RESOLVE_NAME				-7
#define ERROR_SEP2P_INVALID_PREFIX					-8
#define ERROR_SEP2P_ID_OUT_OF_DATE					-9
#define ERROR_SEP2P_NO_RELAY_SERVER_AVAILABLE		-10
#define ERROR_SEP2P_INVALID_SESSION_HANDLE			-11
#define ERROR_SEP2P_SESSION_CLOSED_REMOTE			-12
#define ERROR_SEP2P_SESSION_CLOSED_TIMEOUT			-13
#define ERROR_SEP2P_SESSION_CLOSED_CALLED			-14
#define ERROR_SEP2P_REMOTE_SITE_BUFFER_FULL			-15
#define ERROR_SEP2P_USER_LISTEN_BREAK				-16
#define ERROR_SEP2P_MAX_SESSION						-17
#define ERROR_SEP2P_UDP_PORT_BIND_FAILED				-18
#define ERROR_SEP2P_USER_CONNECT_BREAK				-19
#define ERROR_SEP2P_SESSION_CLOSED_INSUFFICIENT_MEMORY	-20
#define ERROR_SEP2P_STATUS_INTERNAL_FATAL_ERROR				-21
#define ERROR_SEP2P_STATUS_NO_CONNECTED_OBJECT				-22
#define ERROR_SEP2P_STATUS_NO_WORKING_OBJECT				-23
#define ERROR_SEP2P_STATUS_MEM_ALLOC_FAILED					-24
#define ERROR_SEP2P_STATUS_OBJECT_NOT_READY					-25
#define ERROR_SEP2P_STATUS_INVALID_PASSWD					-26
#define ERROR_SEP2P_STATUS_CONNECTION_LOST					-27
#define ERROR_SEP2P_STATUS_DATA_TOO_LOOG					-28
#define ERROR_SEP2P_STATUS_UNKOWN							-29

#endif //// #ifndef _SEP2P_ERROR___INC_H_